### PR TITLE
Got it working! Sorta

### PR DESCRIPTION
**Pull request by cscherrer**
From `mainexample.jl`...

First, some basic setup:

```julia
julia> m = @model X,α,σ begin
           k = size(X,2)
           β ~ Normal(0,α) |> iid(k)
           yhat = X * β
           y ~ For(eachindex(yhat)) do j
               Normal(yhat[j], σ)
           end
       end

julia> X = (a=randn(4), b=randn(4), c=randn(4))
(a = [0.0060002780987986806, 0.9301381133816632, -0.4092078592051705, -0.9026226024582451],
 b = [-2.345050342509911, 0.5602133945837329, 0.8454795029918528, -0.8795508237500409],
 c = [-1.560925438488126, -1.0665459666313923, -0.8309112093063179, 0.18688167416770637],)

julia> params = (α=2.0, σ=1.0)
(α = 2.0,
 σ = 1.0,)
```

Now we set up a `SossMLJModel`, which has arguments

- hyperparameters
- transform
- model
- infer

```julia
julia> mdl = SossMLJ.SossMLJModel(params, X -> (X=MMI.matrix(X),), m, dynamicHMC)
SossMLJModel(
    hyperparams = (α = 2.0, σ = 1.0),
    transform = var"#21#22"(),
    model = @model (X, α, σ) begin
        k = size(X, 2)
        β ~ Normal(0, α) |> iid(k)
        yhat = X * β
        y ~ For(eachindex(yhat)) do j
                Normal(yhat[j], σ)
            end
    end
,
    infer = Soss.dynamicHMC) @605
```

Now we make some fake data

```julia
julia> args = merge(mdl.transform(X), params)
(X = [0.0060002780987986806 -2.345050342509911 -1.560925438488126; 0.9301381133816632 0.5602133945837329 -1.0665459666313923; -0.4092078592051705 0.8454795029918528 -0.8309112093063179; -0.9026226024582451 -0.8795508237500409 0.18688167416770637],
 α = 2.0,
 σ = 1.0,)

julia> truth = rand(m(args))
(k = 3,
 yhat = [-13.934018616014423, -1.8099009549027665, 0.7159691378299029, -2.262507034299712],
 β = [-0.5099401779921846, 3.7840462740595298, 3.239859955754405],
 y = [-13.505542614985984, -1.4783039611756335, 0.5950181151134049, -1.2947091150486087],)

julia> y = truth.y
4-element Array{Float64,1}:
 -13.505542614985984
  -1.4783039611756335
   0.5950181151134049
  -1.2947091150486087
```

and build and fit a machine:

```julia
julia> mach = machine(mdl, X, y)
Machine{SossMLJModel{NamedTuple{,…},…}} @702 trained 0 times.
  args: 
    1:  Source @049 ⏎ `Table{AbstractArray{ScientificTypes.Continuous,1}}`
    2:  Source @799 ⏎ `AbstractArray{ScientificTypes.Continuous,1}`


julia> fit!(mach)
[ Info: Training Machine{SossMLJModel{NamedTuple{,…},…}} @702.
Machine{SossMLJModel{NamedTuple{,…},…}} @702 trained 1 time.
  args: 
    1:  Source @049 ⏎ `Table{AbstractArray{ScientificTypes.Continuous,1}}`
    2:  Source @799 ⏎ `AbstractArray{ScientificTypes.Continuous,1}`
```

Currently this just computes marginals, and in a very kludgy way

```julia
julia> predictor = MLJ.predict(mach, X)
.... # lots of junk
```

It's a vector of `Sampleable`s, so we can do

```julia
julia> rand.(predictor)
4-element Array{Float64,1}:
 -11.418382417286184
  -3.763049874946996
   0.5761280668782105
  -1.1697990939383356
```

It will be much more natural IMO when `rand` can draw across all `y` values

### CODE REVIEW

**Comment by DilumAluthge** [comment]
If I understand correctly, the `MLJModeInterface.predict` method that you've implemented here is giving marginal distributions, right?

Would it be possible for you to also implement the `predict_joint` method that gives the joint distribution across samples?

**Comment by DilumAluthge** [comment]
That way we can demonstrate the difference between `predict` (marginals) and `predict_joint` (joint).

**Comment by DilumAluthge** [comment]
Apart from that, this looks fantastic!

**Comment by DilumAluthge** [comment]
Also, can you rebase on master? I just merged a CompatHelper PR, and I want to make sure that this PR is compatible with the new compat entry.

**Comment by cscherrer** [comment]
> If I understand correctly, the `MLJModeInterface.predict` method that you've implemented here is giving marginal distributions, right?

Yes, that's right.

> Would it be possible for you to also implement the `predict_joint` method that gives the joint distribution across samples?

I'm not sure, I thought I need to have some machinery for everything to propagate correctly. I mean, for example, when we define `fit` and `predict` for a given model, we get the method on `machine`s for free. That won't be the case for `predict_joint`.

Also, will we need to extend `Probabilistic`? We could conceivably just add the `predict_joint` function for `Probabilistic` and assume that some types won't have a method.

> Also, can you rebase on master? I just merged a CompatHelper PR, and I want to make sure that this PR is compatible with the new compat entry.

Sure. This whole this is a WIP anyway, so I'll rebase and we can go from there.

But rebasing will obscure this comment so I'll tag you to make it more likely you see it :) 
@DilumAluthge

**Comment by DilumAluthge** [comment]
Yeah so for now, we’ll need to manually add this machinery ourselves.

See e.g. https://github.com/alan-turing-institute/MLJBase.jl/blob/master/src/operations.jl

We can think of `predict_joint` as being implemented similarly to `predict_mean`, `predict_median`, etc.

Eventually we’ll need to upstream this to MLJModelInterface.jl and MLJBase.jl. And document it in MLJ.jl.

But it will be easier to make the case for upstream that code if we have a working demo in this repo.

**Comment by DilumAluthge** [comment]
If you can implement the `predict_joint` method for models, I’ll work on putting the boilerplate code together to automatically propagate it to machines.

**Pull request merged**
