### PR TITLE
Add the helper code to make the `predict_joint` operation work on machines

### PR DESCRIPTION
**Pull request by DilumAluthge**
@cscherrer Can you test this out and see if it works?

### CODE REVIEW

**Comment by cscherrer** [comment]
Is this supposed to work? Starting from `mainexample.jl`,

```julia
julia> pred2 = SossMLJ.predict_joint(mach, X)
ERROR: MethodError: no method matching predict_joint(::Machine{SossMLJModel{NamedTuple{(:α, :σ),Tuple{Float64,Float64}},var"#7#8",Soss.Model{NamedTuple{(:X, :α, :σ),T} where T<:Tuple,TypeEncoding(begin
    k = size(X, 2)
    β ~ Normal(0, α) |> iid(k)
    yhat = X * β
    y ~ For(eachindex(yhat)) do j
            Normal(yhat[j], σ)
        end
end),TypeEncoding(Main)},typeof(dynamicHMC)}}, ::NamedTuple{(:a, :b, :c),Tuple{Array{Float64,1},Array{Float64,1},Array{Float64,1}}})
Closest candidates are:
  predict_joint(::SossMLJModel, ::Any, ::Any) at /home/chad/git/SossMLJ.jl/src/SossMLJ.jl:104
Stacktrace:
 [1] top-level scope at REPL[34]:1
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```

**Comment by DilumAluthge** [comment]
Hmmm. Let me see why it's not working.

Also, that reminds me: I will add the use of `predict_joint` into `mainexample.jl`.

**Comment by cscherrer** [comment]
I'm getting
```julia
ERROR: UndefVarError: Machine not defined
```

Could be a world age issue from the `eval`?

**Comment by DilumAluthge** [comment]
Oh I see the problem. `Machine` lives in `MLJBase`, not `MMI`.

I'll add a dependency on MLJBase.jl, just temporarily.

Once we have the functionality merged in MLJBase.jl upstream, we should remove the dependency on MLJBase.jl. MLJBase.jl is a pretty heavy package, and packages that implement the MLJ model interface should not import MLJBase.jl. We'll only do so here as a stopgap until https://github.com/alan-turing-institute/MLJBase.jl/pull/392 is merged upstream.

**Comment by cscherrer** [comment]
`AbstractNode` => `MLJBase.AbstractNode`?

**Comment by cscherrer** [comment]
In this:

```julia
predictor_marginal = MLJ.predict(mach, X)
rand.(predictor_marginal)

predictor_joint = MLJ.predict_joint(mach, X)
rand.(predictor_joint)
```

A couple of things...

- `predictor_marginal` returns a `Vector`, so we'll need `rand.(predictor_marginal)`
- But `predictor_joint` returns a `Sampleable`, so here it's just `rand(predictor_joint)`
- We can _usually_ actually do better than `Sampleable`, and have a full `Distribution`

Finally, there's currently some weirdness here:
```julia
function Base.rand(sp::SossMLJPredictor{M}) where {M}
    pars = rand(sp.post)
    args = merge(sp.args, pars)
    return rand(sp.pred(args)).y[1]
end
```

The `[1]` was just to unpack a singleton vector. Removing it gets closer to where we need to be (but we'll still need to wrangle the types a bit)

**Comment by DilumAluthge** [comment]
> But predictor_joint returns a Sampleable, so here it's just rand(predictor_joint)

Cool, I've fixed this locally now, will push in a bit.

**Comment by DilumAluthge** [comment]
> Finally, there's currently some weirdness here:
> 
> ```julia
> function Base.rand(sp::SossMLJPredictor{M}) where {M}
>     pars = rand(sp.post)
>     args = merge(sp.args, pars)
>     return rand(sp.pred(args)).y[1]
> end
> ```
> 
> The `[1]` was just to unpack a singleton vector. Removing it gets closer to where we need to be (but we'll still need to wrangle the types a bit)

Can you explain this issue a little bit?

**Comment by DilumAluthge** [comment]
Also just FYI, starting in Julia 1.4, you can use the `only()` method to unpack a singleton vector.

**Comment by cscherrer** [comment]
> Can you explain this issue a little bit?

Sure, `predict` has this code:
```julia
    map(Tables.rowtable(Xnew)) do xrow
        args = merge(sm.transform([xrow]), sm.hyperparams)
        SossMLJPredictor(sm, post, pred, args)
    end
```

That second line takes a row of `Xnew` and wraps it so it can be interpreted as an entire Table. But then `predict`ing on a Table returns a Vector of `y` values, which in this case is just a singleton. So the end result it you get a vector of singleton vectors. The `[1]` was just to unwrap this as we go.

The `predict_joint` method is much more natural, and the marginal case was really kind of a hack. So we really just need a way to make these consistently typed.

Does that make it clear?

**Pull request merged**
