### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@cscherrer Does this look fine to you?

**Comment by cscherrer** [comment]
I'd guess you might know more about CI than I do. I see some checks failing on the Julia nightly builds, think that's cause for concern?

**Comment by DilumAluthge** [comment]
The failures on nightly are due to an error when trying to `import ResumableFunctions`.

**Comment by cscherrer** [comment]
> The failures on nightly are due to an error when trying to `import ResumableFunctions`.

Ah, great! This was experimental anyway, don't think we're currently using that dependency. So we ought to be able to just remove it

**Pull request merged**
