### PR TITLE
A note to ourself to eventually use `MMI.JointProbabilistic` (once that type exists upstream)

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Nightly failures are not related to this PR.

**Comment by cscherrer** [comment]
@DilumAluthge Will we need to have another type for this? I wonder if it could be enough to just add a `predict_joint` method for `Probabilistic` models, and assume many might not implement it

**Comment by DilumAluthge** [comment]
So, the only benefit of having a type `MMI.JointProbabilistic <: MMI.Probabilistic` is that if I write code that takes in `MMI.JointProbabilistic`, I can assume that the models will implement `MMI.predict_joint`.

Whereas if I write code that takes in `MMI.Probabilistic`, I cannot make that assumption.

**Comment by cscherrer** [comment]
> So, the only benefit of having a type `MMI.JointProbabilistic <: MMI.Probabilistic` is that if I write code that takes in `MMI.JointProbabilistic`, I can assume that the models will implement `MMI.predict_joint`.
> 
> Whereas if I write code that takes in `MMI.Probabilistic`, I cannot make that assumption.

I guess the tradeoff is that just using `MMI.Probabilistic` would allow extending existing models with a `predict_joint` method, which could be useful

**Comment by DilumAluthge** [comment]
> > So, the only benefit of having a type `MMI.JointProbabilistic <: MMI.Probabilistic` is that if I write code that takes in `MMI.JointProbabilistic`, I can assume that the models will implement `MMI.predict_joint`.
> > Whereas if I write code that takes in `MMI.Probabilistic`, I cannot make that assumption.
> 
> I guess the tradeoff is that just using `MMI.Probabilistic` would allow extending existing models with a `predict_joint` method, which could be useful

That's a good point.

What do you think of the docstring I've put here: https://github.com/alan-turing-institute/MLJModelInterface.jl/pull/63/files

Basically, we say that `JointProbabilistic` MUST overload `predict_joint`, and `Probabilistic` MAY overload `predict_joint`.

**Comment by cscherrer** [comment]
> Basically, we say that `JointProbabilistic` MUST overload `predict_joint`, and `Probabilistic` MAY overload `predict_joint`.

Nice! I think that ought to get us the best of both worlds

**Pull request merged**
