### PR TITLE
Some more updates

### LINKED ISSUE #50: TODO: add Bayesian multinomial logistic regression example

### LINKED ISSUE #63: Iris example for multinomial logistic regression
Multi-class classifiers are a pretty popular use case in MLJ, so I think an important next step will be getting an example. I think the Iris example is pretty common.

The Iris dataset is available in RDatasets.jl. 

MLJ has an Iris example here: 

I wrote a tutorial for Turing here: https://turing.ml/dev/tutorials/8-multinomiallogisticregression/

We'll need to do some preprocessing. In particular, we should transform all of the input feature columns by subtracting the column's mean and dividing by the column's standard deviation.

The tricky part is going to be getting `MLJModelInterface.predict` to return a `Vector{UnivariateFinite}`.

We can leave `predict_joint` and `predict_particles` unmodified.

### LINKED ISSUE #66: predict_joint method for Machines
Is this supposed to work?
```julia
julia> predictor_joint = MMI.predict_joint(mach, X)
ERROR: MethodError: no method matching predict_joint(::Machine{SossMLJModel{Soss.Model{NamedTuple{(:X, :s, :t),T} where T<:Tuple,TypeEncoding(begin
    σ ~ HalfNormal(t)
    p = size(X, 2)
    β ~ Normal(0, s) |> iid(p)
    η = X * β
    μ = η
    y ~ For(eachindex(μ)) do i
            Normal(μ[i], σ)
        end
end),TypeEncoding(Main)},var"#5#6",typeof(dynamicHMC),NamedTuple{(:s, :t),Tuple{Float64,Float64}},Symbol}}, ::NamedTuple{(:x1, :x2, :x3, :x4),Tuple{Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Int64,1}}})
Closest candidates are:
  predict_joint(::SossMLJModel, ::Any, ::Any) at /home/chad/git/SossMLJ.jl/src/models.jl:40
Stacktrace:
 [1] top-level scope at REPL[46]:1
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```

There only seems to be one method defined:
```julia
julia> methods(MMI.predict_joint)
# 1 method for generic function "predict_joint":
[1] predict_joint(sm::SossMLJModel, fitresult, Xnew) in SossMLJ at /home/chad/git/SossMLJ.jl/src/models.jl:40
```

### LINKED ISSUE #68: Extending `For` and `UnivariateFinite`
In https://github.com/cscherrer/SossMLJ.jl/issues/65, @ablaom and @DilumAluthge helped clear up the use of `UnivariateFinite`

```julia
julia> v = categorical([:x, :x, :y, :x, :z, :w])
6-element CategoricalArray{Symbol,1,UInt32}:
 :x
 :x
 :y
 :x
 :z
 :w

julia> probs = rand(100, 3);

julia> probs = probs ./ sum(probs, dims=2);

julia> ufvec = UnivariateFinite([:x, :y, :z], probs; pool=v.pool);
```

The supertypes of `ufvec` and of each of its elements are

```julia
julia> supertypes(typeof(ufvec)) |> collect
3-element Array{DataType,1}:
 UnivariateFiniteArray{Multiclass{4},Symbol,UInt32,Float64,1}
 AbstractArray{UnivariateFinite{Multiclass{4},Symbol,UInt32,Float64},1}
 Any

julia> supertypes(typeof(ufvec[1])) |> collect
4-element Array{DataType,1}:
 UnivariateFinite{Multiclass{4},Symbol,UInt32,Float64}
 Distribution{Univariate,MLJBase.NonEuclidean}
 Sampleable{Univariate,MLJBase.NonEuclidean}
 Any
```

This is a great start, but there are still some problems to resolve...

### Not a distribution

Instead of a `Distribution{Vector}`, `ufvec` is a `Vector{Distribution}`. This makes it awkward to work with in a PPL context, where we need to express a joint distribution over all variables.

### No `logpdf` for elements

This works just fine:

```julia
julia> r = rand(ufvec[1])
CategoricalArrays.CategoricalValue{Symbol,UInt32} :y
```

But when we try to evaluate the `logpdf` on this value, things break:

```julia
julia> logpdf(ufvec[1], r)
ERROR: MethodError: no method matching logpdf(::UnivariateFinite{Multiclass{4},Symbol,UInt32,Float64}, ::CategoricalArrays.CategoricalValue{Symbol,UInt32})
Closest candidates are:
  logpdf(::Soss.SymDist, ::Any) at /home/chad/.julia/packages/Soss/FgRzp/src/symbolic/symbolic.jl:69
  logpdf(::Distribution{Univariate,S} where S<:ValueSupport, ::Real) at /home/chad/.julia/packages/Distributions/jFoHB/src/univariates.jl:342
  logpdf(::Distribution{Univariate,S} where S<:ValueSupport, ::AbstractArray) at deprecated.jl:70
```

It seems this might not have been defined?

### Log weights

First, it's often useful to work in terms of log-weights. This can get us more directly to the logpdf without a need to exponentiate and normalize.

### Idiomatic Soss

In Soss, the `For` combinator gives a flexible way to express multivariate distributions. We'd probably write something like

```julia
@model pool begin
    ...
    p ~ ...      # n×k matrix, each row a probability vector
    y ~ For(n) do j
         UnivariateFinite(pool, p[j, :]; pool=pool)
    end
end
```

We could maybe have the implementation optimize this by working in terms of a `UnivariateFiniteArray`, but the extra wrapping makes me wonder if this is really the right abstraction for this case.

Anyway, I'll need to think on this some more...

### LINKED ISSUE #69: TODO: compare accuracy of our Iris model to that of Turing's Iris model
Just as a sanity check, we should check per-class accuracy against that of https://turing.ml/dev/tutorials/8-multinomiallogisticregression/

### PR DESCRIPTION
**Pull request by cscherrer**
Fixes #50 
Fixes #63 
Fixes #66 
Fixes #68 
Fixes #69 

Hi @DilumAluthge , this one is a weird mishmash of stuff:

- Added dependencies for `CategoricalArrays` and `NamedTupleTools`
- Got a rough start on the classification example
- Added a kwargs constructor for `SossMLJModel`
- Changed `variable` kwarg to `response`, still with a default of `:y`
- Rearranged the fields for `SossMLJModel`, hopefully more intuitive to have the model first

Finally, this one I'm not so sure about:
- Removed MLJ dependency from `example-linear-regression.jl`

As an example, it seems weird to load `MLJBase` and `MLJModelInterface`. But I'd also like to avoid the full MLJ dependency if we can. Maybe we should assume users running this example have MLJ installed globally?

### CODE REVIEW

**Comment by cscherrer** [comment]
Oh, and I've confirmed that the linear regression example works :)

**Comment by DilumAluthge** [comment]
I was about to review this but then I saw you push some new commits 🙂 

I've changed it to draft, just so I don't accidentally merge before it's ready.

When you want me to review, just change it back to ready, and ping me?

**Comment by DilumAluthge** [comment]
> As an example, it seems weird to load `MLJBase` and `MLJModelInterface`. But I'd also like to avoid the full MLJ dependency if we can. Maybe we should assume users running this example have MLJ installed globally?

MLJBase reexports all of the relevant stuff from MLJModeInterface.

So, in the examples, just replace all instances of "MLJ" with "MLJBase" and all instances of "MLJModeInterface" with "MLJBase".

That way you don't need the full MLJ just to run the examples.

**Comment by cscherrer** [comment]
@DilumAluthge I'm sure we'll have more changes, but let's see about getting this into master and working from there. Could you please review?

**Review by DilumAluthge — APPROVED** [review]
Looks great to me! We should wait until CI is green before merging, just to be safe.

**Comment by DilumAluthge** [comment]
I've added a test to make sure that the accuracy of the Iris model is above 90%.

We should also look at per-class accuracy, but I'll do that in a separate pull request.

Once CI is green on this PR, I'll merge it.

**Review by DilumAluthge — APPROVED** [review]
Good to merge as soon as CI is green.

**Comment by DilumAluthge** [comment]
Documentation is failing for a silly reason.

**Comment by cscherrer** [comment]
> Good to merge as soon as CI is green.

Does CI work now? I thought we're still waiting on MLJ PRs

**Comment by DilumAluthge** [comment]
> > Good to merge as soon as CI is green.
> 
> Does CI work now? I thought we're still waiting on MLJ PRs

I believe that they've all been merged and registered.

**Pull request merged**
